"""ARINC-424 leg → polyline compiler.

Walks a procedure's ordered legs, resolves each fix
to coordinates via :mod:`procedures_cache.lookup_fix`,
and emits a densely-sampled polyline plus per-fix
annotations the frontend can render directly.

**Leg coverage** (Phase 2):

* ``IF`` — Initial Fix (anchor only, no segment).
* ``TF`` — Track to Fix; great-circle line from
  previous endpoint to this fix.
* ``DF`` — Direct to Fix; same as TF visually.
* ``CF`` — Course to Fix; same as TF.
* ``RF`` — Radius to Fix; arc with center at
  ``center_fix``, sampled at ~1° spacing.
* ``AF`` — DME Arc to Fix; arc center at the
  recommended NAVAID, sampled likewise.
* ``HM`` / ``HF`` / ``HA`` — Holding pattern
  (racetrack); standard 1-min legs at ICAO Cat C
  speed (~140 kt → 4 NM legs), 30 sec turns at
  standard rate.
* ``CA`` / ``VA`` — Course/Heading to Altitude;
  synthetic endpoint generated by climbing along
  ``outbound_mag`` for the leg distance (or 5 NM
  if absent).
* ``CI`` / ``VI`` / ``CR`` / ``VR`` / ``CD`` /
  ``VD`` — Course/Heading to Intercept/Radial/DME;
  same synthetic-distance approach.
* ``FA`` / ``FC`` / ``FD`` / ``FM`` — Fix-anchored
  variants of the above.

Anything else logs and is rendered as a straight
line to the next fix (best-effort fallback).

**Altitude conversion**: every emitted polyline
point goes through
:func:`cesium_app.geodesy.geoid.msl_ft_to_hae_m`.
The geoid module is currently a stub returning 0;
replacing it picks up correct vertical placement
without touching the compiler.
"""
from __future__ import annotations

import logging
import math
from collections.abc import Iterable, Iterator

from pyproj import Geod

from cesium_app.geodesy.geoid import msl_ft_to_hae_m
from cesium_app.store import procedures_cache

logger = logging.getLogger(__name__)

# WGS-84 geodesic; all bearings/distances run on it
# so curved legs follow the actual earth model rather
# than a 2D approximation.
_GEOD = Geod(ellps="WGS84")

# Densification spacing for straight legs and arcs.
_STRAIGHT_LEG_MAX_SEG_M = 5_000.0   # 5 km / ~2.7 NM
_ARC_DEG_PER_SAMPLE = 2.0
_DEFAULT_SYNTHETIC_DIST_NM = 5.0
_HOLD_SEG_LEN_NM = 4.0              # Cat C, 1-min legs
_HOLD_SAMPLES_PER_TURN = 12

# Sanity ceiling: any straight leg longer than this
# almost certainly means we resolved a fix to the
# wrong same-named candidate (e.g., Texas BIRMS vs.
# Alaska BIRMS).  Skip the leg rather than draw a
# 3 000 NM phantom line across the continent.
_MAX_LEG_NM = 200.0

_NM_TO_M = 1852.0


# ─── Fix resolution ─────────────────────────────────

def _resolve_fix(
    fix_id: str,
    *,
    region: str | None = None,
    airport: str | None = None,
    near: tuple[float, float] | None = None,
) -> tuple[float, float] | None:
    if not fix_id:
        return None
    rec = procedures_cache.lookup_fix(
        fix_id, region=region, airport=airport, near=near,
    )
    if rec is None:
        return None
    return rec["lat"], rec["lon"]


# ─── Geodesic helpers ───────────────────────────────

def _great_circle_segment(
    p1: tuple[float, float],
    p2: tuple[float, float],
) -> list[tuple[float, float]]:
    """Densely-sampled great-circle line from p1 to p2."""
    lat1, lon1 = p1
    lat2, lon2 = p2
    _, _, dist_m = _GEOD.inv(lon1, lat1, lon2, lat2)
    n_segs = max(1, int(dist_m // _STRAIGHT_LEG_MAX_SEG_M))
    if n_segs == 1:
        return [p2]
    intermediate = _GEOD.npts(
        lon1, lat1, lon2, lat2, n_segs - 1,
    )
    out = [(lat, lon) for (lon, lat) in intermediate]
    out.append(p2)
    return out


_MAX_ARC_RADIUS_NM = 50.0


def _arc_segment(
    center: tuple[float, float],
    start: tuple[float, float],
    end: tuple[float, float],
    *,
    turn_dir: str,
) -> list[tuple[float, float]] | None:
    """Sample a circular arc on the WGS-84 sphere.

    Computes start/end bearings from the center,
    walks angular distance in 2° steps, and re-projects
    each step to a (lat, lon) point at the same
    radius as ``start`` from ``center``.

    Returns ``None`` if the arc would have an
    implausible radius (>50 NM) — almost always a
    sign that the center fix resolved to the wrong
    candidate.  Caller should fall back to a straight
    line in that case.
    """
    clat, clon = center
    sb, _, radius_m = _GEOD.inv(clon, clat, start[1], start[0])
    eb, _, _ = _GEOD.inv(clon, clat, end[1], end[0])
    if radius_m > _MAX_ARC_RADIUS_NM * _NM_TO_M:
        return None
    # Normalize bearings to [0, 360).
    sb %= 360.0
    eb %= 360.0
    # Decide sweep direction.  ARINC turn dir 'L' =
    # left/CCW (decreasing bearing), 'R' = right/CW
    # (increasing bearing).  Default to the shorter
    # sweep when turn_dir is missing/ambiguous.
    direction = 1.0  # CW (right)
    if turn_dir == "L":
        direction = -1.0
    elif not turn_dir:
        delta_cw = (eb - sb) % 360.0
        if delta_cw > 180.0:
            direction = -1.0
    sweep = (direction * (eb - sb)) % 360.0
    if sweep < 1e-3:
        sweep += 360.0
    n = max(2, int(sweep / _ARC_DEG_PER_SAMPLE))
    out: list[tuple[float, float]] = []
    for i in range(1, n + 1):
        bearing = (sb + direction * sweep * i / n) % 360.0
        lon, lat, _ = _GEOD.fwd(clon, clat, bearing, radius_m)
        out.append((lat, lon))
    return out


def _project(
    origin: tuple[float, float],
    bearing_deg: float,
    distance_m: float,
) -> tuple[float, float]:
    lon, lat, _ = _GEOD.fwd(
        origin[1], origin[0], bearing_deg, distance_m,
    )
    return lat, lon


def _hold_pattern(
    inbound_fix: tuple[float, float],
    inbound_course_deg: float,
    *,
    turn_dir: str,
) -> list[tuple[float, float]]:
    """Synthesize one full racetrack at a fix.

    Produces a closed loop: inbound leg → entry turn
    → outbound leg → exit turn → back to fix.
    Standard 4 NM legs (Cat C 1-min at ~140 kt).
    Turn radius derived from a 2 NM (3.7 km)
    standard-rate-turn at 140 kt — close enough
    visually and consistent across patterns.
    """
    direction = -1.0 if turn_dir == "L" else 1.0
    leg_len_m = _HOLD_SEG_LEN_NM * _NM_TO_M
    turn_radius_m = 2.0 * _NM_TO_M
    # Outbound = reciprocal of inbound; track sign
    # from inbound rather than ARINC ``outbound_mag``
    # so the geometry composes cleanly.
    reciprocal = (inbound_course_deg + 180.0) % 360.0
    perp = (inbound_course_deg + direction * 90.0) % 360.0
    # Fix is the inbound leg's terminal point.  Walk
    # outbound from there to the start of the entry
    # turn.
    far_outbound = _project(inbound_fix, reciprocal, leg_len_m)
    # Entry turn arc: half-circle, center perpendicular
    # to the outbound leg.
    entry_center = _project(far_outbound, perp, turn_radius_m)
    # Outbound leg endpoint after the entry turn:
    # back along the inbound course.
    outbound_end = _project(
        far_outbound, perp, 2 * turn_radius_m,
    )
    near_outbound = _project(
        outbound_end, inbound_course_deg, leg_len_m,
    )
    exit_center = _project(near_outbound, perp, turn_radius_m)

    out: list[tuple[float, float]] = []
    out.extend(
        _great_circle_segment(inbound_fix, far_outbound)
    )
    entry_arc = _arc_segment(
        entry_center, far_outbound, outbound_end,
        turn_dir=turn_dir,
    )
    if entry_arc:
        out.extend(entry_arc)
    out.extend(_great_circle_segment(
        outbound_end, near_outbound,
    ))
    exit_arc = _arc_segment(
        exit_center, near_outbound, inbound_fix,
        turn_dir=turn_dir,
    )
    if exit_arc:
        out.extend(exit_arc)
    return out


# ─── Altitude parsing ───────────────────────────────

def _parse_altitude_ft(s: str | None) -> float | None:
    """ARINC altitude field → feet.

    Encodings observed in CIFP:

    * ``FL250`` → 25 000 ft (flight level × 100).
    * ``05500`` → 5 500 ft (zero-padded MSL).
    * ``+0500`` → 500 ft (signed MSL with sign char).

    Anything unrecognized returns None.
    """
    if not s:
        return None
    s = s.strip()
    if not s:
        return None
    if s.startswith("FL"):
        try:
            return float(s[2:]) * 100.0
        except ValueError:
            return None
    if s[0] in "+-" and s[1:].lstrip("0").isdigit():
        try:
            return float(s)
        except ValueError:
            return None
    if s.lstrip("0").isdigit() or s == "0":
        try:
            return float(s)
        except ValueError:
            return None
    return None


# ─── Per-leg handlers ───────────────────────────────

def _seg_for_straight(
    cur: tuple[float, float] | None,
    fix: tuple[float, float],
) -> list[tuple[float, float]]:
    if cur is None:
        return [fix]
    return _great_circle_segment(cur, fix)


def _seg_for_synthetic_distance(
    cur: tuple[float, float],
    course_deg: float,
    distance_nm: float | None,
) -> tuple[list[tuple[float, float]], tuple[float, float]]:
    """Heading/course leg with no fixed endpoint —
    project a sensible distance and return both the
    segment and the synthetic terminator."""
    nm = distance_nm or _DEFAULT_SYNTHETIC_DIST_NM
    end = _project(cur, course_deg, nm * _NM_TO_M)
    return _great_circle_segment(cur, end), end


def _outbound_course(leg: dict) -> float:
    """Decode ``outbound_mag`` (deg × 10) to degrees."""
    raw = (leg.get("outbound_mag") or "").strip()
    if not raw:
        return 0.0
    try:
        return int(raw) / 10.0
    except ValueError:
        return 0.0


def _route_distance_nm(leg: dict) -> float | None:
    raw = (leg.get("route_dist") or "").strip()
    if not raw:
        return None
    try:
        # Field is NM × 10 for distance, or "T<minutes>"
        # for time-based legs.  Skip time-based.
        if raw.startswith("T"):
            return None
        return int(raw) / 10.0
    except ValueError:
        return None


# ─── Top-level compile ──────────────────────────────

def compile_procedure(proc: dict) -> dict | None:
    """Compile one procedure's legs into a polyline.

    Returns ``{procedure_id, polyline, fixes, bbox}``
    or ``None`` if no fix in the procedure could be
    resolved (typically a non-US procedure that
    references fixes outside the FAA CIFP database).
    """
    airport = proc.get("airport")
    # Anchor fix lookups to the airport position so
    # ambiguous identifiers resolve to the local
    # candidate, not a same-named fix on the far side
    # of the continent.
    airport_pos = (
        procedures_cache.airport_position(airport)
        if airport else None
    )
    polyline: list[list[float]] = []
    fixes: list[dict] = []
    anchors: list[tuple[int, float]] = []
    cur_pos: tuple[float, float] | None = None
    cur_course: float = 0.0

    for leg in proc.get("legs", []):
        leg_type = (leg.get("leg_type") or "").upper()
        fix_id = leg.get("fix_ident") or ""
        fix_region = leg.get("fix_region") or None
        # Bias by current position if we have one
        # (more local), else airport position.
        proximity_ref = cur_pos or airport_pos
        target = _resolve_fix(
            fix_id, region=fix_region, airport=airport,
            near=proximity_ref,
        )
        # Reject obvious mis-resolutions: a "straight"
        # leg whose endpoint is hundreds of NM from
        # the previous fix indicates a wrong-region
        # match.  Drop the target so the leg either
        # synthesizes (heading-based) or skips.
        if (target is not None and cur_pos is not None
                and leg_type in (
                    "TF", "DF", "CF", "FA", "FC", "FD",
                    "FM", "RF", "AF",
                )):
            _, _, dist_m = _GEOD.inv(
                cur_pos[1], cur_pos[0],
                target[1], target[0],
            )
            if dist_m > _MAX_LEG_NM * _NM_TO_M:
                logger.debug(
                    "Skip leg %s.%s: %s → %s is %.0f NM "
                    "(>%.0f NM, likely wrong fix)",
                    proc["id"], leg.get("seq"),
                    cur_pos, target,
                    dist_m / _NM_TO_M, _MAX_LEG_NM,
                )
                target = None
        # Prepare a per-fix annotation regardless of
        # whether the geometry math succeeds.
        alt1 = _parse_altitude_ft(leg.get("alt_1"))
        alt2 = _parse_altitude_ft(leg.get("alt_2"))
        speed = leg.get("speed_limit", "").strip()
        annotation = {
            "fix_ident": fix_id,
            "leg_type": leg_type,
            "alt_1_ft": alt1,
            "alt_2_ft": alt2,
            "alt_desc": leg.get("alt_desc", "").strip(),
            "speed_kt": int(speed) if speed.isdigit() else None,
        }

        seg: list[tuple[float, float]] = []
        if leg_type in ("IF",):
            if target is None:
                continue
            cur_pos = target
            seg = [target]
        elif leg_type in ("TF", "DF", "CF",
                          "FA", "FC", "FD", "FM"):
            if target is None:
                # Best-effort: if we know course and
                # distance, project synthetically.
                if cur_pos is not None:
                    course = _outbound_course(leg)
                    seg, cur_pos = _seg_for_synthetic_distance(
                        cur_pos, course,
                        _route_distance_nm(leg),
                    )
                    cur_course = course
                else:
                    continue
            else:
                seg = _seg_for_straight(cur_pos, target)
                if cur_pos is not None:
                    bearing, _, _ = _GEOD.inv(
                        cur_pos[1], cur_pos[0],
                        target[1], target[0],
                    )
                    cur_course = bearing % 360.0
                cur_pos = target
        elif leg_type in ("RF", "AF"):
            if target is None or cur_pos is None:
                continue
            center_id = (leg.get("center_fix") or "").strip()
            center_region = (
                leg.get("center_region") or None
            )
            navaid_id = (leg.get("rec_navaid") or "").strip()
            navaid_region = (
                leg.get("navaid_region") or None
            )
            # RF center is the explicit center_fix;
            # AF center is the recommended NAVAID.
            if leg_type == "RF":
                center = _resolve_fix(
                    center_id, region=center_region,
                    airport=airport,
                )
            else:
                center = _resolve_fix(
                    navaid_id, region=navaid_region,
                    airport=airport,
                )
            arc = None
            if center is not None:
                arc = _arc_segment(
                    center, cur_pos, target,
                    turn_dir=(leg.get("turn_dir") or "").upper(),
                )
            seg = arc if arc is not None else (
                _seg_for_straight(cur_pos, target)
            )
            cur_pos = target
        elif leg_type in ("HM", "HF", "HA"):
            if target is None:
                continue
            inbound = (
                cur_course
                if cur_pos is not None
                else _outbound_course(leg)
            )
            seg = _hold_pattern(
                target, inbound,
                turn_dir=(leg.get("turn_dir") or "").upper(),
            )
            cur_pos = target
        elif leg_type in ("CA", "VA", "CI", "VI",
                          "CR", "VR", "CD", "VD",
                          "VM", "FM"):
            if cur_pos is None:
                continue
            course = _outbound_course(leg)
            seg, cur_pos = _seg_for_synthetic_distance(
                cur_pos, course,
                _route_distance_nm(leg),
            )
            cur_course = course
        else:
            # Unknown leg type — fall back to straight
            # if we can resolve the fix; otherwise skip.
            if target is None or cur_pos is None:
                if target is not None:
                    cur_pos = target
                continue
            seg = _seg_for_straight(cur_pos, target)
            cur_pos = target

        # Append the geometry with placeholder altitudes;
        # the interpolation pass below fills in the real
        # vertical profile once all anchor altitudes are
        # known.  Placeholder stays 0 so even a
        # procedure with no constrained fixes still
        # renders (flat on the ellipsoid) rather than
        # failing silently.
        for lat, lon in seg:
            polyline.append([lat, lon, 0.0, 0.0])

        # Annotate the segment's endpoint as a fix.
        if seg:
            end_lat, end_lon = seg[-1]
            annotation.update({
                "lat": end_lat, "lon": end_lon,
                "polyline_idx": len(polyline) - 1,
                "alt_hae_m": 0.0,  # filled below
            })
            fixes.append(annotation)
            # Record an altitude anchor at this fix's
            # endpoint if CIFP published a constraint.
            if alt1 is not None:
                anchors.append(
                    (len(polyline) - 1, float(alt1)),
                )

    if not polyline:
        return None

    # Fill in the vertical profile by linear
    # interpolation across cumulative path distance
    # between altitude-anchored fixes.  The idea: a
    # published procedure gives the pilot a constraint
    # at each named fix; between constraints the
    # aircraft descends / climbs continuously along the
    # path, not in step-functions.  Before the first
    # anchor and after the last, hold flat at the
    # nearest anchor's altitude.
    _fill_altitudes(polyline, anchors, fixes)

    lats = [pt[0] for pt in polyline]
    lons = [pt[1] for pt in polyline]
    return {
        "procedure_id": proc["id"],
        "polyline": polyline,
        "fixes": fixes,
        "bbox": (min(lats), max(lats), min(lons), max(lons)),
    }


def _fill_altitudes(
    polyline: list[list[float]],
    anchors: list[tuple[int, float]],
    fixes: list[dict],
) -> None:
    """Interpolate MSL altitude along cumulative
    path distance, anchor-to-anchor, then convert
    each sample to HAE.

    - No anchors at all: polyline stays at 0.0 MSL.
    - One anchor: level flight at that altitude.
    - Multi-anchor: linear descent/climb between
      consecutive anchors, flat before first and
      after last.
    """
    if not polyline:
        return
    n = len(polyline)
    # Pre-compute cumulative great-circle distance
    # along the polyline so interpolation weighs samples
    # by actual earth-surface distance, not just index.
    cum = [0.0] * n
    for i in range(1, n):
        _, _, d = _GEOD.inv(
            polyline[i - 1][1], polyline[i - 1][0],
            polyline[i][1], polyline[i][0],
        )
        cum[i] = cum[i - 1] + d

    alt_msl = [0.0] * n
    if not anchors:
        pass
    elif len(anchors) == 1:
        only = anchors[0][1]
        for i in range(n):
            alt_msl[i] = only
    else:
        anchors = sorted(anchors, key=lambda a: a[0])
        # Before first anchor: hold.
        first_idx, first_alt = anchors[0]
        for i in range(0, first_idx + 1):
            alt_msl[i] = first_alt
        # Between consecutive anchors: linear by distance.
        for (ia, alta), (ib, altb) in zip(
            anchors, anchors[1:]
        ):
            d_span = cum[ib] - cum[ia]
            if d_span <= 0.0:
                # Degenerate / same-point anchors.
                for i in range(ia, ib + 1):
                    alt_msl[i] = altb
                continue
            for i in range(ia, ib + 1):
                t = (cum[i] - cum[ia]) / d_span
                alt_msl[i] = alta + t * (altb - alta)
        # After last anchor: hold.
        last_idx, last_alt = anchors[-1]
        for i in range(last_idx, n):
            alt_msl[i] = last_alt

    # Apply HAE conversion per sample.
    for i in range(n):
        lat, lon = polyline[i][0], polyline[i][1]
        msl_ft = alt_msl[i]
        hae_m = msl_ft_to_hae_m(msl_ft, lat, lon)
        polyline[i][2] = hae_m
        polyline[i][3] = msl_ft

    # Update each fix annotation's HAE to match the
    # interpolated profile at its polyline index.
    for f in fixes:
        idx = f.get("polyline_idx")
        if idx is None or idx >= n:
            continue
        f["alt_hae_m"] = polyline[idx][2]


def compile_all(
    procs: Iterable[dict],
) -> Iterator[dict]:
    """Compile every procedure; skip empty results."""
    for proc in procs:
        try:
            geom = compile_procedure(proc)
        except Exception:  # noqa: BLE001
            logger.exception(
                "Compile failed for %s; skipping",
                proc.get("id"),
            )
            continue
        if geom is not None:
            yield geom
